[package]
name = "console-events"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_events"
path = "src/lib.rs"

[[bin]]
name = "console-events"
path = "src/bin/console-events.rs"

[dependencies]
console-core-places = { workspace = true }
console-program-contract.workspace = true
console-core-never.workspace = true
console-onscreen.workspace = true
console-core-reconnect.workspace = true
console-core-external-programs.workspace = true
console-program-lifetime.workspace = true
console-core-number-conversion.workspace = true
rustix.workspace = true
console-waiting.workspace = true

[lints]
workspace = true
