[package]
name = "console-repository"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_repository"
path = "src/lib.rs"

[dependencies]
console-core-never.workspace = true

[dev-dependencies]
console-core-number-conversion.workspace = true
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "3", features = ["full", "visit"] }

[lints]
workspace = true
