[package]
name = "console-device"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_device"
path = "src/lib.rs"

[[bin]]
name = "console-deploy"
path = "src/bin/console-deploy.rs"

[[bin]]
name = "console-migrate"
path = "src/bin/console-migrate.rs"

[dependencies]
console-external-programs.workspace = true
console-file-writing.workspace = true
console-never.workspace = true
console-program-contract.workspace = true
console-program-runtime.workspace = true
console-repository.workspace = true
console-session.workspace = true

[lints]
workspace = true
