pulse.rules = [
    {
        matches = [ { application.process.binary = "electron" } ]
        actions = {
            update-props = {
                state.restore-props = false
            }
        }
    }
]
