[package]
name = "console-flows"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_flows"
path = "src/lib.rs"

[dev-dependencies]
console-controller.workspace = true
console-door.workspace = true
console-guide.workspace = true
console-pad.workspace = true
console-stage.workspace = true
evdev = "0.13"

[lints]
workspace = true
