[package]
name = "console-draw-surface"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_draw_surface"
path = "src/lib.rs"

[[bin]]
name = "surface-spike"
path = "src/bin/surface-spike.rs"

[dependencies]
console-core-geometry.workspace = true
console-screen.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-response-times.workspace = true

rustix.workspace = true

wayland-client = "0.31"

wayland-protocols = { version = "0.32", features = ["client", "staging"] }

wayland-protocols-wlr = { version = "0.3", features = ["client"] }

xkbcommon = "0.9"

[lints]
workspace = true
