[package]
name = "console-input-touchscreen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "console-tap"
path = "src/bin/tap.rs"

[dependencies]
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-screen.workspace = true
console-input-event-devices.workspace = true

[lints]
workspace = true
