[package]
name = "console-login-window"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_login_window"
path = "src/lib.rs"

[[bin]]
name = "login-window"
path = "src/bin/login-window.rs"

[dependencies]
console-applications.workspace = true
console-core-external-programs.workspace = true
console-core-ini-files.workspace = true
console-core-atomic-writes.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-core-internal-programs.workspace = true
console-core-places.workspace = true
console-login-session.workspace = true
console-program-lifetime.workspace = true

[lints]
workspace = true
