[package]
name = "console-input-language"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_input_language"
path = "src/lib.rs"

[[bin]]
name = "language-switch"
path = "src/bin/language-switch.rs"

[dependencies]
console-input-alphabets.workspace = true
console-compositor.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-core-walking.workspace = true
console-core-places.workspace = true

[lints]
workspace = true
