[package]
name = "console-bus"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_bus"
path = "src/lib.rs"

[dependencies]
console-core-never.workspace = true
console-core-number-conversion.workspace = true
rustix.workspace = true

[dev-dependencies]
console-core-external-programs.workspace = true

[lints]
workspace = true
