[package]
name = "console-control-center"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_control_center"
path = "src/lib.rs"

[[bin]]
name = "console-control-center"
path = "src/bin/console-control-center.rs"

[dependencies]
console-core-color.workspace = true
console-core-fonts.workspace = true
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-core-shapes.workspace = true
console-core-internal-programs.workspace = true
console-program-lifetime.workspace = true
console-onscreen.workspace = true
console-draw-painting.workspace = true
console-draw-surface.workspace = true

[lints]
workspace = true
