[package]
name = "console-bar"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_bar"
path = "src/lib.rs"

[[bin]]
name = "bar-notice"
path = "src/bin/bar-notice.rs"

[[bin]]
name = "bar-say"
path = "src/bin/bar-say.rs"

[dependencies]
console-number.workspace = true
console-again.workspace = true
console-defaults.workspace = true
console-notices.workspace = true
console-panel.workspace = true
libc = "0.2"
serde_json = "1"

[lints]
workspace = true
