[package]
name = "console-input-focus"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_input_focus"
path = "src/lib.rs"

[dependencies]
console-core-words.workspace = true
console-input-gamepad.workspace = true
console-core-never.workspace = true
console-input-event-devices.workspace = true

[lints]
workspace = true
