[package]
name = "console-downloads"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_downloads"
path = "src/lib.rs"

[[bin]]
name = "downloads"
path = "src/bin/downloads.rs"

[[bin]]
name = "downloads-find"
path = "src/bin/downloads-find.rs"

[[bin]]
name = "downloads-get"
path = "src/bin/downloads-get.rs"

[[bin]]
name = "downloads-format"
path = "src/bin/downloads-format.rs"

[dependencies]
console-core-atomic-writes.workspace = true
console-core-places.workspace = true
console-core-never.workspace = true
console-core-localization.workspace = true
console-core-words.workspace = true
console-program-contract.workspace = true
console-core-external-programs.workspace = true
console-core-number-conversion.workspace = true
serde_json = "1"
console-music-player.workspace = true
console-books.workspace = true
console-panel.workspace = true

[lints]
workspace = true
