[package]
name = "console-core-checksums"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_core_checksums"
path = "src/lib.rs"

[dependencies]
console-core-never.workspace = true
console-core-number-conversion.workspace = true

[lints]
workspace = true
