[package]
name = "console-onscreen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_onscreen"
path = "src/lib.rs"

[dependencies]
console-compositor.workspace = true
console-core-atomic-writes.workspace = true
console-core-never.workspace = true
serde_json = "1"

[lints]
workspace = true
