[package]
name = "console-test-flows"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_test_flows"
path = "src/lib.rs"

[dev-dependencies]
console-input-controller.workspace = true
console-onscreen.workspace = true
console-button-guide.workspace = true
console-input-gamepad.workspace = true
console-test-stages.workspace = true
evdev = "0.13"

[lints]
workspace = true
