[package]
name = "console-draw-painting"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_draw_painting"
path = "src/lib.rs"

[dependencies]
console-core-color.workspace = true
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true
console-core-shapes.workspace = true

cairo-rs = "0.22"
pango = "0.22"
pangocairo = "0.22"

[lints]
workspace = true
