[package]
name = "console-core-qr-codes"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-number-conversion.workspace = true

[lints]
workspace = true
