[package]
name = "console-panels"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_panels"
path = "src/lib.rs"

[[bin]]
name = "console-panels"
path = "src/bin/console-panels.rs"

[dependencies]
console-input-mapping.workspace = true
console-calculator.workspace = true
console-calendar.workspace = true
console-downloads.workspace = true
console-files.workspace = true
console-forecast.workspace = true
console-launcher.workspace = true
console-music.workspace = true
console-core-internal-programs.workspace = true
console-core-never.workspace = true
console-notifications.workspace = true
console-panel.workspace = true
console-settings.workspace = true
console-media-viewer.workspace = true
console-response-times.workspace = true
rustix.workspace = true

[lints]
workspace = true
