[package]
name = "console-program-contract"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_program_contract"
path = "src/lib.rs"

[dependencies]
console-core-external-programs.workspace = true
console-core-never.workspace = true

[lints]
workspace = true
