[package]
name = "console-media-viewer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_media_viewer"
path = "src/lib.rs"

[[bin]]
name = "viewer"
path = "src/bin/viewer.rs"

[dependencies]
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-localization.workspace = true
console-core-walking.workspace = true
console-core-words.workspace = true
console-program-contract.workspace = true
console-core-external-programs.workspace = true
console-core-number-conversion.workspace = true
console-core-places.workspace = true
console-panel.workspace = true
console-content-types.workspace = true
console-pictures.workspace = true
console-music-player.workspace = true
console-program-lifetime.workspace = true
console-core-shapes.workspace = true


[dev-dependencies]
console-waiting.workspace = true
console-settings.workspace = true
console-test-stages.workspace = true

[lints]
workspace = true
