[package]
name = "console-test-stages"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_test_stages"
path = "src/lib.rs"

[dependencies]
console-core-atomic-writes.workspace = true
console-device-name.workspace = true
console-compositor.workspace = true
console-core-external-programs.workspace = true
console-core-ini-files.workspace = true
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-walking.workspace = true
console-core-places.workspace = true
console-core-words.workspace = true
console-waiting.workspace = true
console-program-lifetime.workspace = true
console-onscreen.workspace = true
console-core-number-conversion.workspace = true
console-how-far.workspace = true
cairo-rs = { version = "0.22", features = ["png"] }
console-input-event-devices.workspace = true
console-core-color.workspace = true
console-input-bindings.workspace = true
console-input-controller.workspace = true
console-input-gamepad = { workspace = true, features = ["read"] }
console-screen.workspace = true
console-panel.workspace = true
console-response-times.workspace = true
console-notifications.workspace = true
serde_json = "1"
console-signals = { path = "../console-signals" }
rustix.workspace = true

[lints]
workspace = true
