[package]
name = "console-controller"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_controller"
path = "src/lib.rs"

[[bin]]
name = "stick-scroll"
path = "src/bin/stick-scroll.rs"

[[bin]]
name = "game-return"
path = "src/bin/game-return.rs"

[dependencies]
evdev = "0.13"

[dev-dependencies]
console-pad.workspace = true
