[package]
name = "console-test-checks"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_test_checks"
path = "src/lib.rs"

[[bin]]
name = "console-check"
path = "src/bin/console-check.rs"

[dependencies]
console-core-temporary-directories.workspace = true
console-architecture.workspace = true
console-awake.workspace = true
console-concurrency.workspace = true
console-core-atomic-writes.workspace = true
console-input-gamepad.workspace = true
console-home-screen.workspace = true
console-core-external-programs.workspace = true
console-core-ini-files.workspace = true
console-core-geometry.workspace = true
console-core-number-conversion.workspace = true
console-core-never.workspace = true
console-core-places.workspace = true
console-compositor.workspace = true
console-input-bindings.workspace = true
console-input-controller.workspace = true
console-music-player.workspace = true
console-notifications.workspace = true
console-status-bar.workspace = true
console-screen.workspace = true
serde_json = "1"

console-program-lifetime.workspace = true
console-resume.workspace = true
console-settings.workspace = true
console-waiting.workspace = true
console-onscreen.workspace = true
console-events.workspace = true
console-repository.workspace = true
console-panel.workspace = true
console-test-stages.workspace = true
console-response-times.workspace = true
console-input-event-devices.workspace = true
console-login-greeter.workspace = true
console-login-pattern.workspace = true
console-login-window.workspace = true
serde = { version = "1", features = ["derive"] }
toml = { version = "0.9", default-features = false, features = ["parse", "serde"] }

[lints]
workspace = true
