[package]
name = "console-panel"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_panel"
path = "src/lib.rs"

[[bin]]
name = "console-confirm"
path = "src/bin/console-confirm.rs"

[[bin]]
name = "console-put-away"
path = "src/bin/console-put-away.rs"

[[bin]]
name = "second-picker"
path = "src/bin/second-picker.rs"

[[bin]]
name = "panel-pictures"
path = "src/bin/panel-pictures.rs"

[dependencies]
console-core-atomic-writes.workspace = true
console-core-color.workspace = true
console-concurrency.workspace = true
console-core-fonts.workspace = true
console-core-shapes.workspace = true
console-draw-painting.workspace = true
console-draw-surface.workspace = true
console-core-words.workspace = true
console-program-lifetime.workspace = true
console-core-external-programs.workspace = true
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-internal-programs.workspace = true
console-core-places.workspace = true
console-waiting.workspace = true
console-core-number-conversion.workspace = true
console-compositor.workspace = true
console-onscreen.workspace = true
console-events.workspace = true
console-program-contract.workspace = true
console-response-times.workspace = true
console-pictures.workspace = true
console-sound-effects.workspace = true
console-signals = { path = "../console-signals" }
rustix.workspace = true
serde_json = "1"

[dev-dependencies]
console-repository.workspace = true
console-core-temporary-directories.workspace = true
console-test-stages.workspace = true

[lints]
workspace = true
