[package]
name = "console-files"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_files"
path = "src/lib.rs"

[[bin]]
name = "files"
path = "src/bin/files.rs"

[[bin]]
name = "files-thumbs"
path = "src/bin/files-thumbs.rs"

[[bin]]
name = "files-unzip"
path = "src/bin/files-unzip.rs"

[[bin]]
name = "console-screenshot"
path = "src/bin/console-screenshot.rs"

[dependencies]
console-core-atomic-writes.workspace = true
console-applications.workspace = true
console-content-types.workspace = true
console-core-checksums.workspace = true
console-core-never.workspace = true
console-core-places.workspace = true
console-core-words.workspace = true
console-program-contract.workspace = true
console-core-external-programs.workspace = true
console-core-number-conversion.workspace = true
console-panel.workspace = true

[lints]
workspace = true
