[package]
name = "console-input-keyboard"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"

[lib]
name = "console_input_keyboard"
path = "src/lib.rs"

[[bin]]
name = "console-keyboard"
path = "src/bin/keyboard.rs"
required-features = ["port"]

[[bin]]
name = "keyboard-toggle"
path = "src/bin/toggle.rs"

[[bin]]
name = "keyboard-show"
path = "src/bin/show.rs"

[features]
default = ["port"]
port = [
    "dep:console-input-alphabets",
    "dep:console-input-gamepad",
    "dep:console-input-focus",
    "dep:console-response-times",
    "dep:console-input-event-devices",
    "dep:rustix",
    "dep:xkbcommon",
    "dep:cairo-rs",
    "dep:pango",
    "dep:pangocairo",
    "dep:wayland-client",
    "dep:wayland-protocols-wlr",
    "dep:wayland-protocols-misc",
]

[dependencies]
console-core-number-conversion.workspace = true
console-core-color.workspace = true
console-core-words.workspace = true
console-program-contract.workspace = true
console-program-runtime.workspace = true
console-core-external-programs.workspace = true
console-core-geometry.workspace = true
console-core-never.workspace = true
console-core-walking.workspace = true

console-input-gamepad = { workspace = true, optional = true }
console-input-focus = { workspace = true, optional = true }
console-response-times = { workspace = true, optional = true }
console-input-alphabets = { workspace = true, optional = true }
console-core-places.workspace = true
console-input-event-devices = { workspace = true, optional = true }
rustix = { workspace = true, optional = true }
xkbcommon = { version = "0.9", optional = true }
cairo-rs = { version = "0.22", optional = true }
pango = { version = "0.22", optional = true }
pangocairo = { version = "0.22", optional = true }
wayland-client = { version = "0.31", optional = true }
wayland-protocols-wlr = { version = "0.3", features = ["client"], optional = true }
wayland-protocols-misc = { version = "0.3", features = ["client"], optional = true }

[dev-dependencies]
console-input-controller.workspace = true

[lints]
workspace = true
