[package]
name = "console-defaults"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_defaults"
path = "src/lib.rs"

[[bin]]
name = "console-engine"
path = "src/bin/console-engine.rs"

[[bin]]
name = "console-browser"
path = "src/bin/console-browser.rs"

[dependencies]
serde_json = "1"
