[package]
name = "console-notifications"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_notifications"
path = "src/lib.rs"

[[bin]]
name = "notifications-panel"
path = "src/bin/notifications-panel.rs"

[[bin]]
name = "console-notify"
path = "src/bin/console-notify.rs"

[[bin]]
name = "console-say"
path = "src/bin/console-say.rs"

[[bin]]
name = "console-report-crash"
path = "src/bin/console-report-crash.rs"

[[bin]]
name = "console-updating"
path = "src/bin/console-updating.rs"

[dependencies]
console-core-fonts.workspace = true
console-bus.workspace = true
console-events.workspace = true
console-core-number-conversion.workspace = true
console-core-color.workspace = true
console-core-geometry.workspace = true
console-core-shapes.workspace = true
console-draw-painting.workspace = true
console-draw-surface.workspace = true
console-program-lifetime.workspace = true
console-core-places = { workspace = true }
console-core-external-programs.workspace = true
console-core-never.workspace = true
console-core-words.workspace = true
console-waiting.workspace = true
console-panel.workspace = true
console-onscreen.workspace = true
console-core-atomic-writes.workspace = true
console-program-contract.workspace = true
rustix.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
