[package]
name = "console-child-processes"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "console_child_processes"
path = "src/lib.rs"

[dependencies]
console-never.workspace = true
libc = "0.2"

[dev-dependencies]
console-external-programs.workspace = true

[lints]
workspace = true
